### ISSUE TITLE
Inferring schema for NonEmptySet[String] fails

### ISSUE THREAD

**Issue by vovateleport** [andyglow/scala-jsonschema#112]
Hi,
`val schema = Json.schema[NonEmptySet[String]]`
fails with 
```
[error] exception during macro expansion: 
[error] scala.ScalaReflectionException: type Type is not a class
[error] 	at scala.reflect.api.Symbols$SymbolApi.asClass(Symbols.scala:284)
[error] 	at scala.reflect.api.Symbols$SymbolApi.asClass$(Symbols.scala:284)
[error] 	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:99)
[error] 	at com.github.andyglow.jsonschema.UTypeDecorations$TypeDecoration$.fromAnnotations(UTypeDecorations.scala:25)
[error] 	at com.github.andyglow.jsonschema.UTypeDecorations$TypeDecoration$.apply(UTypeDecorations.scala:44)
[error] 	at com.github.andyglow.jsonschema.Macroses.deriveInternal(Macroses.scala:70)
[error] 	at com.github.andyglow.jsonschema.Macroses.deriveSchema(Macroses.scala:52)
[error]     val schema = Json.schema[NonEmptySet[String]]
```

jsonschema: 0.6.1
cats: 2.3.0
scala: 2.13.4

**Comment by andyglow** [comment]
Hi, there is a separate module that adds support for cats types
Please take a look at this test here
https://github.com/andyglow/scala-jsonschema/blob/master/modules/cats/src/test/scala/com/github/andyglow/jsonschema/CatsSupportSpec.scala

Here is the dependency
```
  // cats support
  "com.github.andyglow" %% "scala-jsonschema-cats" % <version>,     
```

**Comment by vovateleport** [comment]
I see. 
I added dependency, but didn't import `com.github.andyglow.jsonschema.CatsSupport._` - that was the issue.

But `Json.schema[NonEmptySet[String]]` still fails to compile,
wrapping NonEmptySet in case class 
```
case class Aaa(arr: NonEmptySet[String])
Json.schema[Aaa]
```
compiles ok.

**Comment by andyglow** [comment]
got it, ok, thanks for report
i'll check it
