### ISSUE TITLE
Macro Expansion Failing with Generic Class

### ISSUE THREAD

**Issue by IlyaHalsky** [andyglow/scala-jsonschema#191]
**Describe the bug**
Macro failing on `head of empty list` when using macro in unintended way

**To Reproduce**
```scala
import com.github.andyglow.jsonschema.Macroses
import json.Schema

import scala.language.experimental.macros

abstract class WithSchema[T](implicit val schema: Schema[T]) {
  val a: Schema[T] = schema // Use schema in runtime
}

object ExampleApp extends App {
  implicit def getSchema[T]: Schema[T] = macro Macroses.deriveSchema[T]

  case class Company(name: String)
  class A extends WithSchema[Company]
}
```

**Expected behavior**
Code compiles, calling A.a returns generated schema

**Actual results**
```
exception during macro expansion: 
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:662)
	at scala.collection.immutable.Nil$.head(List.scala:661)
	at com.github.andyglow.jsonschema.UDictionaries$DictionaryExtractor.$anonfun$unapply$1(UDictionaries.scala:12)
	at com.github.andyglow.jsonschema.UCommons$OptionCompanionOps.whenever(UCommons.scala:161)
	at com.github.andyglow.jsonschema.UDictionaries$DictionaryExtractor.unapply(UDictionaries.scala:10)
	at com.github.andyglow.jsonschema.Macroses.genTree$1(Macroses.scala:100)
	at com.github.andyglow.jsonschema.Macroses.$anonfun$resolve$1(Macroses.scala:110)
	at com.github.andyglow.jsonschema.UImplicits$Implicit.getOrElse(UImplicits.scala:81)
	at com.github.andyglow.jsonschema.Macroses.resolve(Macroses.scala:110)
	at com.github.andyglow.jsonschema.Macroses.deriveInternal(Macroses.scala:77)
	at com.github.andyglow.jsonschema.Macroses.deriveSchema(Macroses.scala:54)
```

**Versions:**
 - jsonschema version - 0.7.3
 - scala version - 2.13.6

**Additional context**
I'm trying to implement API for my REST API framework which requires programmer to write minimal amount of code.
I plan to use `WithSchema` in common place, where I don't know exact types. In order to do so I need `io.circe.Decoder`, `io.circe.Encoder` and `Schema` inside common class. I was able to overcome Decoder and Encoder by using `abstract class WithDecoder[T](implicit val schema: Decoder[T])` and `io.circe.generic.AutoDerivation` and was tying to hack yours by doing similar thing. This issue might be related to #23, but I'm not sure. 

Thanks for the help in advance.

**Comment by andyglow** [comment]
Hello, @IlyaHalsky 
Please try `0.7.4`.. it has one extra `scala-jsonschema-derive` module.
Also please check this test on how to use this feature
https://github.com/andyglow/scala-jsonschema/blob/master/modules/derived/src/test/scala/json/schema/derived/DerivedSchemaSpec.scala

**Comment by IlyaHalsky** [comment]
Thanks a lot, works like a charm
